import { defineConfig } from 'tsup';

export default defineConfig({
  entry: ['src/cli.ts'],
  format: ['esm'],
  splitting: false,
  sourcemap: true,
  clean: true,
  target: 'node20',
  treeshake: true,
  banner: { js: '#!/usr/bin/env node' },
  noExternal: [],
  external: [
    '@catlabtech/webcvt-core',
    '@catlabtech/webcvt-container-mp3',
    '@catlabtech/webcvt-container-wav',
    '@catlabtech/webcvt-container-flac',
    '@catlabtech/webcvt-container-ogg',
    '@catlabtech/webcvt-container-aac',
    '@catlabtech/webcvt-container-mp4',
    '@catlabtech/webcvt-container-webm',
    '@catlabtech/webcvt-container-mkv',
    '@catlabtech/webcvt-container-ts',
    '@catlabtech/webcvt-image-canvas',
    '@catlabtech/webcvt-image-svg',
    '@catlabtech/webcvt-image-animation',
    '@catlabtech/webcvt-image-legacy',
    '@catlabtech/webcvt-data-text',
    '@catlabtech/webcvt-archive-zip',
    '@catlabtech/webcvt-subtitle',
    '@catlabtech/webcvt-backend-wasm',
  ],
});
