/**
 * Synthetic GIF89a builder for tests.
 *
 * Uses the production encodeLzw to build frame pixel data, so the
 * generated bytes are valid GIF89a that parseGif can parse.
 */

import { encodeLzw } from '../gif-lzw.ts';
import { ascii, concat, u8, u16le } from './bytes.ts';

export interface GifFrameSpec {
  x?: number;
  y?: number;
  w: number;
  h: number;
  /** Colour palette for this frame (RGB triplets). If omitted, uses a 4-colour default. */
  palette?: number[];
  /** Indexed pixel values (one per pixel). */
  indexed: number[];
  /** Frame delay in hundredths of a second (default 10 = 100ms). */
  delay?: number;
  /** GIF disposal method: 0=none, 1=leave, 2=background, 3=previous. Default 1. */
  disposal?: number;
  /** If set, the index to be transparent. */
  transparent?: number;
  /** If true, frame is interlaced (rows stored in 4-pass order). */
  interlaced?: boolean;
}

export interface BuildGifOptions {
  canvasW: number;
  canvasH: number;
  /** Global Color Table as RGB triplets. If omitted, uses a 4-colour default. */
  gct?: number[];
  frames: GifFrameSpec[];
  /** Loop count for NETSCAPE2.0. Omit to not include NETSCAPE2.0. */
  loopCount?: number;
  pixelAspectRatio?: number;
  backgroundColorIndex?: number;
}

const DEFAULT_GCT = [
  0,
  0,
  0, // 0 = black
  255,
  255,
  255, // 1 = white
  255,
  0,
  0, // 2 = red
  0,
  255,
  0, // 3 = green
];

/**
 * Build a complete GIF89a byte stream from the given spec.
 * The resulting bytes are valid input for parseGif.
 */
export function buildGif(opts: BuildGifOptions): Uint8Array {
  const gct = opts.gct ?? DEFAULT_GCT;
  const gctEntries = Math.ceil(gct.length / 3);
  // Pad GCT to next power of 2
  const gctPow2 = nextPow2(Math.max(2, gctEntries));
  const gctSizePow = Math.max(0, Math.round(Math.log2(gctPow2)) - 1);
  const gctFlag = 1;
  const packed = (gctFlag << 7) | (gctSizePow & 0x07);

  const parts: Uint8Array[] = [];

  // Header
  parts.push(ascii('GIF89a'));

  // Logical Screen Descriptor
  const lsd = new Uint8Array(7);
  lsd[0] = opts.canvasW & 0xff;
  lsd[1] = (opts.canvasW >> 8) & 0xff;
  lsd[2] = opts.canvasH & 0xff;
  lsd[3] = (opts.canvasH >> 8) & 0xff;
  lsd[4] = packed;
  lsd[5] = opts.backgroundColorIndex ?? 0;
  lsd[6] = opts.pixelAspectRatio ?? 0;
  parts.push(lsd);

  // Global Color Table (padded)
  const gctBytes = new Uint8Array(gctPow2 * 3);
  for (let i = 0; i < gct.length; i++) gctBytes[i] = gct[i] ?? 0;
  parts.push(gctBytes);

  // NETSCAPE2.0 extension if loopCount specified
  if (opts.loopCount !== undefined) {
    parts.push(buildNetscapeExt(opts.loopCount));
  }

  // Frames
  for (const frame of opts.frames) {
    const delay = frame.delay ?? 10;
    const disposal = frame.disposal ?? 1;
    const transparent = frame.transparent;

    // GCE
    const transparentFlag = transparent !== undefined ? 1 : 0;
    const transIdx = transparent ?? 0;
    const gcePacked = (disposal << 2) | transparentFlag;
    parts.push(
      new Uint8Array([
        0x21,
        0xf9,
        0x04,
        gcePacked,
        delay & 0xff,
        (delay >> 8) & 0xff,
        transIdx,
        0x00,
      ]),
    );

    // Choose LCT if frame has its own palette
    const framePalette = frame.palette;
    let lctFlag = 0;
    let lctSizePow = 0;

    if (framePalette) {
      const lctEntries = nextPow2(Math.max(2, Math.ceil(framePalette.length / 3)));
      lctSizePow = Math.max(0, Math.round(Math.log2(lctEntries)) - 1);
      lctFlag = 1;
    }

    const interlaceFlag = frame.interlaced ? 1 : 0;
    const imgPacked = (lctFlag << 7) | (interlaceFlag << 6) | (lctSizePow & 0x07);

    // Image Descriptor
    const imgDesc = new Uint8Array(10);
    imgDesc[0] = 0x2c;
    imgDesc[1] = (frame.x ?? 0) & 0xff;
    imgDesc[2] = ((frame.x ?? 0) >> 8) & 0xff;
    imgDesc[3] = (frame.y ?? 0) & 0xff;
    imgDesc[4] = ((frame.y ?? 0) >> 8) & 0xff;
    imgDesc[5] = frame.w & 0xff;
    imgDesc[6] = (frame.w >> 8) & 0xff;
    imgDesc[7] = frame.h & 0xff;
    imgDesc[8] = (frame.h >> 8) & 0xff;
    imgDesc[9] = imgPacked;
    parts.push(imgDesc);

    // LCT if present
    if (framePalette && lctFlag) {
      const lctEntries = 2 << lctSizePow;
      const lct = new Uint8Array(lctEntries * 3);
      for (let i = 0; i < framePalette.length; i++) lct[i] = framePalette[i] ?? 0;
      parts.push(lct);
    }

    // LZW pixel data
    const activePaletteSize = framePalette
      ? nextPow2(Math.max(2, Math.ceil(framePalette.length / 3)))
      : gctPow2;
    const lzwMinCodeSize = Math.max(2, Math.ceil(Math.log2(Math.max(2, activePaletteSize))));
    const pixels = new Uint8Array(frame.indexed);
    const encoded = encodeLzw(pixels, lzwMinCodeSize);
    parts.push(encoded);
  }

  // Trailer
  parts.push(new Uint8Array([0x3b]));

  return concat(...parts);
}

function nextPow2(n: number): number {
  if (n <= 2) return 2;
  let p = 2;
  while (p < n) p <<= 1;
  return p;
}

function buildNetscapeExt(loopCount: number): Uint8Array {
  const out = new Uint8Array(19);
  out[0] = 0x21;
  out[1] = 0xff;
  out[2] = 0x0b;
  const id = ascii('NETSCAPE2.0');
  out.set(id, 3);
  out[14] = 0x03;
  out[15] = 0x01;
  out[16] = loopCount & 0xff;
  out[17] = (loopCount >> 8) & 0xff;
  out[18] = 0x00;
  return out;
}
